INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Телевизор', 43000,  3);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Микроволновая печь', 4700, 11);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Клавиатура', 3800, 6);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Компьютерная мышь', 1300, 17);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Чайник', 5600, 8);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Монитор', 22000, 24);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Холодильник', 120000, 1);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Ноутбук', 67000, 37);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Камера', 1500, 54);
INSERT INTO online_electronics_store.products (name, price, quantity) VALUES ( 'Микрофон', 800, 36);