version: '3'

services:
  app:
    build: .
    container_name: homework05
    volumes:
      - ./files/:/files/
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge